CREATE TABLE Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(100) NOT NULL UNIQUE,
                       birthYear int CHECK ( birthYear > 1900) NOT NULL ,
                       address varchar NOT NULL
);

CREATE TABLE Book(
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     person_id int REFERENCES Person(id) ON DELETE SET NULL,
                     title varchar(300) NOT NULL,
                     author varchar(100) NOT NULL,
                     age int NOT NULL
);